SELECT 
VSET_FCY.ALT_CD                   	AS HOSPITAL
,CV_PATDIS.MEDICAL_RECORD_NUMBER  	AS PERSON_ID--MEDICAL_RECORD_NUMBER
,CV_PATDIS.PATIENT_ID             	AS ENCNTR_ID--PATIENT_ID
,CV_PATDIS.PATIENT_ID             	AS PFT_ENCNTR_ID--PATIENT_ID
,CV_PATDIS.MEDICAL_RECORD_NUMBER  	AS MRN--MEDICAL_RECORD_NUMBER
,CV_PATDIS.FIN                    	AS FIN--FIN
,CV_PATDIS.PATIENT_FIRST_NAME     	AS NAME_FIRST--PATIENT_FIRST_NAME
,CV_PATDIS.PATIENT_LAST_NAME      	AS NAME_LAST---PATIENT_LAST_NAME
,CV_PATDIS.PATIENT_MIDDLE_NAME    	AS NAME_MIDDLE--PATIENT_MIDDLE_NAME
,CV_PATDIS.SEX                 		AS GENDER--SEX
,TO_DATE(CV_PATDIS.BIRTH_DATE  ,'MMDDYYYY')                 AS DOB--BIRTH_DATE
,CV_PATDIS.ADMISSION_TS            	AS ADMIT_DT_TM--ADMISSION_TS
,CV_PATDIS.DISCHARGE_TS            	AS DISCH_DT_TM--DISCHARGE_TS
,NULL                             	AS ED_ARRIVAL_DT_TM
,NULL                             	AS ED_DEPART_DT_TM
,TO_DATE(CV_PATDIS.UPDATEDATE,'MMDDYYYY') AS UPDT_DT_TM
,CV_PATDIS.FINANCIALCLASS         	AS FINANCIAL_CLASS--FINANCIALCLASS
,PMSTR1.PAYER_DESCRIPTION     		AS PRIMARY_PAYOR
,PMSTR.PAYER_DESCRIPTION     		AS SECONDARY_PAYOR
,PMSTR1.PAYOR_GROUP1    			AS PRIMARY_PAYOR_1_GROUP
,PMSTR1.PAYOR_GROUP2    			AS PRIMARY_PAYOR_2_GROUP
,PMSTR.PAYOR_GROUP1    				AS SECONDARY_PAYOR_1_GROUP
,PMSTR.PAYOR_GROUP2    				AS SECONDARY_PAYOR_2_GROUP
,CV_PATDIS.NURSINGSTATION			AS DISCHARGE_UNIT---NURSINGSTATION
FROM PCE_QE16_OPER_PRD_ZOOM..CV_PATDISCH AS CV_PATDIS
LEFT JOIN PCE_QE16_SLP_PRD_DM..VAL_SET_DIM VSET_FCY 
ON VSET_FCY.CD = CV_PATDIS.COMPANY_ID AND VSET_FCY.COHRT_ID = 'FACILITY_CODES'
LEFT JOIN PCE_QE16_SLP_PRD_DM..PAYMSTR_DIM PMSTR1
ON CV_PATDIS.PRIMARY_PAYER_CODE = PMSTR1.PAYER_CODE AND PMSTR1.COMPANY_ID = CV_PATDIS.COMPANY_ID
LEFT JOIN PCE_QE16_SLP_PRD_DM..PAYMSTR_DIM PMSTR
ON CV_PATDIS.SECONDARY_PAYER_CODE = PMSTR.PAYER_CODE AND PMSTR.COMPANY_ID = CV_PATDIS.COMPANY_ID
WHERE DATE(CV_PATDIS.DISCHARGE_TS) = (CURRENT_DATE - 1)
        AND CV_PATDIS.TOTAL_CHARGES_IND = 1
        AND UPPER(CV_PATDIS.COMPANY_ID) NOT LIKE '%PROF'
        AND UPPER(CV_PATDIS.COMPANY_ID) <> 'MMG'
        AND UPPER(CV_PATDIS.INPATIENT_OUTPATIENT_FLAG) = 'I'
		AND UPPER(CV_PATDIS.RCRD_PCE_CST_SRC_NM) = 'CERNER'
