\set ON_ERROR_STOP ON;

--Purge prior records from PATBILL Table
delete from cv_patbill where rcrd_pce_cst_src_nm in ('CERNER','STLUKES');

--Insert the records from Stage PatBill 
insert into cv_patbill
(
	rcrd_load_type
       , rcrd_isrt_pcs_nm
       , rcrd_isrt_ts
       , rcrd_udt_pcs_nm
       , rcrd_udt_ts
       , rcrd_src_isrt_id
       , rcrd_src_isrt_ts
       , rcrd_src_udt_id
       , rcrd_src_udt_ts
       , rcrd_src_file_nm
       , rcrd_btch_audt_id
       , rcrd_pce_cst_nm
       , rcrd_pce_cst_src_nm
       , company_id
       , patient_id
       , service_date
       , charge_code
       , quantity
       , total_charge
       , total_variable_cost
       , total_fixed_cost
       , cpt_code
       , revenue_code
       , ordering_practitioner_code
       , cpt_modifier_1
       , cpt_modifier_2
       , cpt_modifier_3
       , cpt_modifier_4
       , dept
       , postdate
       , unitcharge
       , invoiceid
       , performingphysician
       , cpt4full
       , subaccount
       , chargecodedesc
       , financialclass
       , payorplancode
       , updatedate
       , sourcesystem
       , raw_chargcode
       , organization
       , billitemid
       , chargeitemid
       , ndc
       , ndcunits
       , ndcunitofmeasure
       , financial_charge_primary_key
       , hcpcs
       , charge_type
       , professional_charge_indicator
       , diagnosis_1
       , diagnosis_2
       , diagnosis_3
       , diagnosis_4
       , diagnosis_5
       , service_location_facility
       , service_location_building
       , service_location_nurse_unit
       , service_location_room
       , service_location_bed
       , accommodation
       , late_charge_status
       , activity_type
       , service_resource
       , manual_indicator
       , charge_status
       , price_schedule
       , tier_group
       , provider_speciality
       , activity_datetime
       , service_datetime
       , adjusted_datetime
       , credited_datetime
       , cancelled_datetime
       , gl_activity_datetime
       , gl_interface_datetime
       , work_rvu
       , charge_problem
       , hcpcs_desc
       , encounter_location_facility
       , encounter_location_building
       , encounter_location_nurse_unit
       , encounter_location_room
       , encounter_location_bed
       , ndc_description
       , reclass_indicator
)
SELECT rcrd_load_type
       , rcrd_isrt_pcs_nm
       , rcrd_isrt_ts
       , rcrd_udt_pcs_nm
       , rcrd_udt_ts
       , rcrd_src_isrt_id
       , rcrd_src_isrt_ts
       , rcrd_src_udt_id
       , rcrd_src_udt_ts
       , rcrd_src_file_nm
       , rcrd_btch_audt_id
       , rcrd_pce_cst_nm
       , rcrd_pce_cst_src_nm
       , company_id
       , patient_id
       , service_date
       , charge_code
       , quantity
       , total_charge
       , total_variable_cost
       , total_fixed_cost
       , cpt_code
       , revenue_code
       , ordering_practitioner_code
       , cpt_modifier_1
       , cpt_modifier_2
       , cpt_modifier_3
       , cpt_modifier_4
       , dept
       , postdate
       , unitcharge
       , invoiceid
       , performingphysician
       , cpt4full
       , subaccount
       , chargecodedesc
       , financialclass
       , payorplancode
       , updatedate
       , sourcesystem
       , raw_chargcode
       , organization
       , billitemid
       , chargeitemid
       , ndc
       , ndcunits
       , ndcunitofmeasure
       , financial_charge_primary_key
       , hcpcs
       , charge_type
       , professional_charge_indicator
       , diagnosis_1
       , diagnosis_2
       , diagnosis_3
       , diagnosis_4
       , diagnosis_5
       , service_location_facility
       , service_location_building
       , service_location_nurse_unit
       , service_location_room
       , service_location_bed
       , accommodation
       , late_charge_status
       , activity_type
       , service_resource
       , manual_indicator
       , charge_status
       , price_schedule
       , tier_group
       , provider_speciality
       , activity_datetime
       , service_datetime
       , adjusted_datetime
       , credited_datetime
       , cancelled_datetime
       , gl_activity_datetime
       , gl_interface_datetime
       , work_rvu
       , charge_problem
       , hcpcs_desc
       , encounter_location_facility
       , encounter_location_building
       , encounter_location_nurse_unit
       , encounter_location_room
       , encounter_location_bed
       , ndc_description
       , reclass_indicator

  FROM pce_qe16_oper_prd_zoom..stg_patbill_cerner;

generate statistics on cv_patbill;

\unset ON_ERROR_STOP

